version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - TZ=Asia/Tokyo
    volumes:
      - ./localstack:/tmp/localstack
      - ./initaws:/docker-entrypoint-initaws.d
    ports:
      - 4566:4566
